name: Build Documentation

on:
  push:
    branches:
      - main
    paths-ignore: 
      - 'docs/**'
#      - '.github/**'
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      # Install Doxygen
      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1
        with:
          version: "1.15.0"

      # Maintain folder structure
      - name: Ensure doc output directories exist
        run: |
          mkdir -p docs/NanoXLSX.Formatting

      # Generate docs for NanoXLSX.Formatting
      - name: Generate NanoXLSX.Formatting docs
        run: |
          cd NanoXLSX.Formatting/Documentation
          doxygen documentation.doxygen

      # Upload docs artifact
      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
